# nginx proxy address - http://172.17.0.1:8101

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  netbox:
    image: netboxcommunity/netbox:latest
    container_name: netbox-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - netbox
    ports:
      - "8101:8080"
    environment:
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./rootfs/data/netbox:/data
      - ./rootfs/config/netbox:/config
    depends_on:
      - netbox-db

  netbox-db:
    image: postgres:16-alpine
    container_name: netbox-db
    restart: unless-stopped
    logging: *default-logging
    networks:
      - netbox
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-netbox}
      POSTGRES_USER: ${DB_USER_NAME:-netbox}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - ./rootfs/data/db/postgres/netbox:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  netbox:
    external: false
